# Generated by Django 6.0.7 on 2026-08-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_created_at_note_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
