# Generated by Django 6.0.7 on 2026-08-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='subject_colour',
            field=models.CharField(blank=True, default='#000000', max_length=7),
        ),
    ]
