# Generated by Django 6.0.7 on 2026-09-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='pomodoro_goal',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
