# Generated by Django 6.0.7 on 2026-09-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='checkbox',
            new_name='checked',
        ),
    ]
