# Generated by Django 5.2.11 on 2026-03-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
