# Generated by Django 5.2.11 on 2026-03-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_react_delete_todoitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='employee',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='react',
            name='department',
        ),
        migrations.AddField(
            model_name='react',
            name='detail',
            field=models.CharField(default='exit', max_length=500),
            preserve_default=False,
        ),
    ]
