# Generated by Django 5.2.11 on 2026-03-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_rename_employee_react_name_remove_react_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='name',
            new_name='employee',
        ),
    ]
