# Generated by Django 5.2.11 on 2026-03-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_rename_name_react_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='detail',
            new_name='department',
        ),
    ]
