# Generated by Django 6.0.7 on 2026-09-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('session_type', models.CharField(choices=[('work', 'Focus'), ('short_break', 'Short break'), ('long_break', 'Long break')], default='work', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('task_label', models.CharField(blank=True, max_length=200)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='PomodoroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('work_minutes', models.PositiveIntegerField(default=25)),
                ('short_break_minutes', models.PositiveIntegerField(default=5)),
                ('long_break_minutes', models.PositiveIntegerField(default=15)),
                ('sessions_before_long_break', models.PositiveIntegerField(default=4)),
            ],
        ),
    ]
