# Generated by Django 6.0.7 on 2026-09-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0003_alter_pomodorosession_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodorosettings',
            name='sessions_before_long_break',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
