# Generated by Django 6.0.7 on 2026-09-30 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0004_alter_pomodorosettings_sessions_before_long_break'),
        ('users', '0009_merge_20260923_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodorosettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
