# Generated by Django 6.0.7 on 2026-09-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_firstname_user_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferredName',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
