# Generated by Django 6.0.7 on 2026-09-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_preferredname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferredName',
            field=models.CharField(default=models.CharField(default='Anonymous', max_length=100), max_length=100),
        ),
    ]
