# Generated by Django 6.0.7 on 2026-09-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_preferredname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferredName',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
