# Generated by Django 6.0.7 on 2026-09-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_preferredname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferredName',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
