# Generated by Django 6.0.7 on 2026-09-23 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_picture'),
        ('users', '0008_alter_user_preferredname'),
    ]

    operations = [
    ]
